version: '2'
services:
  leases-app:
    image: ghacupha/leases:0.0.1-SNAPSHOT
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      #- SPRING_DATASOURCE_URL=jdbc:postgresql://leases-postgresql:5432/leases
      - SPRING_DATASOURCE_URL=${LOCAL_PG_SERVER}/leases
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://leases-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://leases-elasticsearch:9200
      - PG_DATABASE_DEV_USER=${PG_DATABASE_DEV_USER}
      - PG_DATABASE_DEV_PASSWORD=${PG_DATABASE_DEV_PASSWORD}
      - LOCAL_PG_SERVER=${LOCAL_PG_SERVER}
    ports:
      - 22000:22000
  #  leases-postgresql:
  #    extends:
  #      file: postgresql.yml
  #      service: leases-postgresql
  leases-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: leases-elasticsearch
