version: '2'
services:
  leases-app:
    image: leases
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://leases-postgresql:5432/leases
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://leases-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://leases-elasticsearch:9200
    ports:
      - 22000:22000
  leases-postgresql:
    extends:
      file: postgresql.yml
      service: leases-postgresql
  leases-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: leases-elasticsearch
