version: '2'
services:
  leases-postgresql:
    image: postgres:12.3
    # volumes:
    #     - ~/volumes/jhipster/leases/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${PG_DATABASE_DEV_USER}
      - POSTGRES_PASSWORD=${PG_DATABASE_DEV_PASSWORD}
      - POSTGRES_DB=leases
    ports:
      - 5432:5432
