export const enum LeasesFileModelType {
  CURRENCY_LIST = 'CURRENCY_LIST',

  CONTRACTUAL_LEASE_RENTAL = 'CONTRACTUAL_LEASE_RENTAL',

  LEASE_DETAILS = 'LEASE_DETAILS',

  LEASE_RENTAL = 'LEASE_RENTAL',
}
